

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: waterlevel_svc
      POSTGRES_PASSWORD: G1g1.supomfuop
      POSTGRES_DB: WaterLevel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://youruser:yourpassword@db/WaterLevel
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
